CMakeLists.txt

`vorbisfile` target does not exist and this breaks the build on Android with CMake.
This seems to be referring to vorbisfile.c, which is part of `libvorbisidec`.
Removing it fixes the build.

Fix for build with SUPPORT_OGG on Android

---

CMakeLists.txt

So that users of this target can write `#include <SDL_mixer.h>` instead of `#include <include/SDL_mixer.h>`.

CMakeLists.txt: expose include directory as target_include_directories

---

src/codecs/native_midi/native_midi_macosx.c

Isn't should be the debug log print here? Right now, this makes some errors when using C90 compatibility being enforced.
Replacement for #303

native_midi_macosx.c: fixed the C90 warning

---

src/codecs/music_fluidsynth.c

The original code of the FLUIDSYNTH_LoadMusic() looks like the scaring lasagna with the bad visuality which is a source of various memory leak errors caused by the human factor.
I made it look better and move all clean-up into the `FLUIDSYNTH_Delete()` by adding all checks for every stage in the middle.
--- 
P.S. In addition I want to allow the FluidSynth to work with the Float32 format too (it can!) (when the Mixer was open with the AUDIO_F32-like format). This should avoid clipping when using the AUDIO_S16 as a source format. I'll make this change as a separate pull request which will depend on this.

music_fluidsynth.c: Refactor the FLUIDSYNTH_LoadMusic() call

---

Makefile.in
configure.ac

When building SDL1-mixer with slibtool and parallel make (`-j2` or greater) it fails when slibtool if faster than `mkinstalldirs` while GNU libtool is slower and just happens to work. This can be fixed by making an explicit dependency on a sentinel file created in the build directory. This has already been fixed in SDL2-mixer.
```
rlibtool: error logged in slbt_exec_compile(), line 158: path not found: build/.libs/.
make: *** [Makefile:137: build/effect_position.lo] Error 2
make: *** Waiting for unfinished jobs....
mkdir -p -- build
```
Also see:
https://github.com/libsdl-org/SDL_mixer/commit/b432a23ac02ef83e9114f70e81738b30c0853cf9
https://github.com/libsdl-org/SDL/commit/39e8e3951cff8a6f6c284c1dcd0e3e5d66438f81
https://github.com/libsdl-org/SDL-1.2/pull/840

build: Fix parallel make with slibtool.

---

configure.ac

Fix the following build failure when building statically with --enable-music-ogg-tremor:
```
libtool: link: /tmp/instance-0/output-1/host/bin/arm-linux-gcc -o build/playwave build/playwave.o -I/tmp/instance-0/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -static  -L/tmp/instance-0/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib build/.libs/libSDL_mixer.a -L/tmp/instance-0/output-1/host/bin/../arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib /tmp/instance-0/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libSDL.a /tmp/instance-0/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libasound.a -lrt -ldl /tmp/instance-0/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libts.a …
```

configure.ac: fix static linking with tremor

---

src/mixer.c

`Mix_VolumeChunk()` doesn't check if the chunk passed to it is NULL. If that happens, a crash with a segfault will follow.
Would returning `-1` as a value for the previous volume be acceptable?

Add a NULL-Check to Mix_VolumeChunk()

---

CMakeLists.txt

Remove if (ANDROID) on CMake file
It is not possible to use with CMake under Linux (Tested with manjaro 21.1.6).

Fix CMake build fail

---

.github/workflows/linux.yml
CMakeLists.txt

**Add github Action and fix CMake build fail.**
Tested with manjaro 21.1.6 and [github action](https://github.com/bensuperpc/SDL_mixer/actions/runs/1454991608) (**Ubuntu CI**) in my git repository.
Github action:
- Build with CMake (**Release** mode) and make
- Build With GCC 9 and Clang 10 (ubuntu-latest = ubuntu-20.04 now)
- Build with static or shared lib (CMake only)
Fix wrong header path with SDL2 and bump CMake to 3.0.0 (#314)
Signed-off-by: Bensuperpc <bensuperpc@gmail.com>

Add github Action and fix CMake build fail

---

src/codecs/timidity/timidity.c

Resolves #334
An argument of property in Timidity config can be surrounded with `"` or `'` characters to prevent splitting into several arguments if it contains spaces or other delimiter characters.
If an argument itself contains `"` characters it should be surrounded with `'` characters and vice versa.

Added support of quoted strings in Timidity config

---

src/codecs/music_mpg123.c
src/codecs/music_ogg.c

fixes:
src/codecs/music_mpg123.c:66:1: warning: missing field 'mpg123_close' initializer [-Wmissing-field-initializers]
src/codecs/music_ogg.c:66:1: warning: missing field 'ov_clear' initializer [-Wmissing-field-initializers]

resolve -Wmissing-field-initializers warnings

---

src/mixer.c

I found this crash case a while ago at MixerX. It happen because the "fragment" wasn't properly updated and left being NULL. That leads an attempt to dereferrence it while it has NULL inside.

mixer.c: Fixed the crash at the Mix_LoadMusic_RW

---

src/codecs/music_wav.c

- ensure the structs used in ParseFMT are packed without padding
- use stack to load the format information
- ensure ParseFMT does not read outside of the allocated memory in case of EXT_CODE

improve ParseFMT

---

src/codecs/music_flac.c
src/codecs/music_fluidsynth.c
src/codecs/music_mikmod.c
src/codecs/music_modplug.c
src/codecs/music_mpg123.c
src/codecs/music_ogg.c
src/codecs/music_opus.c
src/codecs/music_xmp.c

Addition to https://github.com/libsdl-org/SDL_mixer/commit/143b0bbfd50654af667c87143c1a2d69ef80f151
EDIT: As was discussed below, I changed the entire goal of this PR:
----
C standard gives guarantee they will be NULLed by default:
https://port70.net/~nsz/c/c89/c89-draft.html#3.5.7
> If an object that has static storage duration is not initialized explicitly, it is initialized implicitly as if every member that has arithmetic type were assigned 0 and every member that has pointer type were assigned a null pointer constant. If an object that has automatic storage duration is not initialized explicitly, its value is indeterminate.

Remove all initializers from static loader arrays

---

src/codecs/music_xmp.c

To get the proper title of the song, it should be taken from another place. The field was actually taken is a copyright field.

music_xmp.c: Fixed the correctness of meta-tags

---

src/codecs/music_wav.c

- fix 'improve ParseFMT': SDL_RWseek returns -1 not 0 on error
- propagate error when SDL_RWseek returns -1
- always check the result of SDL_RWseek againts -1

fix handling of SDL_RWseek in music_wav.c

---

src/codecs/music_mpg123.c

Accessing the `music->handle` after MPEG123_Delete(music) will lead to crash

music_mpg123.c: Fixed memory access after free

---

CMakeLists.txt

SDL2_mixer.dll doesn't have any version information when built with CMake because version.rc wasn't included as a source file.

Include version.rc in Windows CMake builds

---

native_midi/native_midi_macosx.c

This PR fixes a compilation error on OS X Tiger (PowerPC).
Based on the surrounding code, I'd say it is likely that someone refactored `song->` to `retval->` but forgot to update the PowerPC case to match, but didn't encounter the build failure because they weren't on a PowerPC machine.

Compilation fix for OS X/PowerPC

---

src/codecs/music_xmp.c

This way, we avoid loading the whole module into memory.
CC: @Wohlstand

music_xmp: use xmp_load_module_from_callbacks() if available

---

src/codecs/music_ogg.c

SDL_RWseek(), in both SDL-1.2 and SDL-2.0, returns the current offset upon
success and not NOERROR (0), therefore it behaves like `lseek`, not `fseek`
which vorbis expects. The current version seems to have worked so far by
luck.
CC: @Wohlstand

music_ogg: fix sdl_seek_func() return value (SDL-2.0 / main)

---

music_ogg.c

SDL_RWseek(), in both SDL-1.2 and SDL-2.0, returns the current offset upon
success and not NOERROR (0), therefore it behaves like `lseek`, not `fseek`
which vorbis expects. The current version seems to have worked so far by
luck.
CC: @Wohlstand

music_ogg: fix sdl_seek_func() return value (SDL-1.2)

---

.github/workflows/main.yml
CMakeLists.txt
src/codecs/music_modplug.c
src/codecs/music_ogg.c

Fix enabling external libraries with CMake

---

CMakeLists.txt

- Fixed using SDL_mixer as subproject with cmake's add_subdirectory with disabled BUILD_SHARED_LIBS
- Removed checks for ANDROID when detecting SDL2 or SDL2-static
From now we can use SDL_mixer with cmake in this way:
```
option(BUILD_SHARED_LIBS "Build the library as a shared library" OFF)
option(BUILD_SAMPLES "Build the sample program(s)" OFF)
option(SDL_STATIC_PIC "Static version of the library should be built with Position Independent Code" ON) #for x86_64 Android build
add_subdirectory(external/SDL)
add_subdirectory(external/SDL_mixer)
add_subdirectory(path_to_your_project)
```

cmake: fixed the use of SDL_mixer with disabled BUILD_SHARED_LIBS

---

include/SDL_mixer.h
src/mixer.c
src/music.c

In some cases we need to set the overall volume level. 
For now we have only two ways:
- modify chunk's volume
- modify channel's volume
Both are bad in case when we need to modify all played now sounds and all sounds that will be played in the future.
To solve this problem I suggest new function Mix_MasterVolume(int) which works with single static variable int master_volume.
This variable is used in mix_channels/music_mixer to calculate current volume level.

Implemented the master volume feature.

---

CHANGES.txt
src/mixer.c

Update `Mix_Init()` to return all the initialized sample/music loaders as mentioned here:
https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_9.html
```
Returns: a bitmask of all the currently initted sample/music loaders. 
```
Note that the same page mentions:
```
You may call this multiple times, which will actually require you to call
Mix_Quit just once to clean up.
```
The above statement seems to match the implementation.
However, the `Mix_Quit()` [documentation page](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_10.html#SEC10) seems to be conflict with the `Mix_Init()` documentation:
```
You should call this function for each time Mix_Init was called, otherwise it
may not free all the dynamic library resources until the program ends. This is
done so that multiple …
```

Update Mix_Init() return value to match documentation

---

src/codecs/mp3utils.h

It was done a while ago but is no longer actual.
Thanks to @sezero for the notice!

mp3utils.h: Fixed an outdated header title

---

configure
configure.ac
src/codecs/music_ogg_stb.c
src/codecs/stb_vorbis/stb_vorbis.h

- Keeps the original stb_vorbis as intact as possible so
that future updates from mainstream would be painless.
- Reduces STB_VORBIS_MAX_CHANNELS from 16 to 6 (objections?)
- Adds several missing libm function overrides,
- SDL_mixer now requires SDL >= 2.0.9 because of SDL_exp()
- Fixes slow loads and leaks in start_decoder:
https://github.com/nothings/stb/pull/1174
- Fixes submap array out-of-bounds indexing bug:
https://github.com/nothings/stb/pull/1312
- Replace signed overflow clamps with unsigned overflow:
https://github.com/nothings/stb/issues/1168
- Replaces alloca() usage with setup_malloc() (from libxmp.)
- Fixes '-Wmaybe-uninitialized' warnings in get_seek_page_info:
https://github.com/nothings/stb/pull/1172
- A minor UBSan fix and suppression: …

Rebase and update stb_vorbis.h to SDL_sound's version :

---

src/codecs/load_voc.c

Clang Code Model noticed the possible recognition of `v.size` as an uninitialized data which may lead to unexpected behavior. Also, make sure `SDL_malloc()` will never be called with a zero value of `v.rest`, and avoid leading division by zero (when `*audio_len` is divided by `v.size`)

load_voc.c: Fixed Clang warning

---

src/music.c

Avoid a infinite loop / hang if the user's program has the music paused when trying to free it. If the music isn't active, it will never finish fading out.

Don't wait for the music to fade out in Mix_FreeMusic if it is inactive

---

Makefile.in
configure
configure.ac
sdl2_mixer-config.cmake.in

* autotools: Move mandatory dependencies from EXTRA_LDFLAGS to MIXER_LIBS
Autotools variables whose names end with _LDFLAGS are usually for
linker options such as -Wl,--export-dynamic which would not be
appropriate to copy into the pkg-config or CMake metadata.
Move these dependencies into a separate _LIBS variable, which is
conventionally a list of -L and -l options (only) and *can* be copied
into pkg-config or CMake metadata. This follows the same pattern as
IMG_LIBS and TTF_LIBS in SDL_image and SDL_ttf.
Exclude SDL_LIBS from this, because the CMake metadata has a special
case for finding SDL, and linking to a different SDL causes link failure
on our macOS CI. Link SDL via $(SDL_LIBS) instead.
* sdl2_mixer-config.cmake.in: Use MIXER_LIBS for static linking
We can't rely on all …

Fix static linking to Autotools builds using CMake

---

configure.ac

Plain Autoconf only defines PACKAGE_NAME, PACKAGE_VERSION and similar
substitution variables, to which Automake adds PACKAGE and VERSION.
SDL_mixer doesn't use Automake, so it doesn't have the VERSION required
by our SDL2_mixer.pc.in (and SDL2_mixer.spec.in) unless we set it
explicitly.
Resolves: https://github.com/libsdl-org/SDL_mixer/issues/421  
Fixes: 52d3f2c "Rewrite CMake build script"

configure.ac: Make sure to set VERSION

---

acinclude/ax_compute_relative_paths.m4
acinclude/ax_normalize_path.m4
acinclude/ax_recursive_eval.m4
configure
configure.ac
sdl2_mixer-config.cmake.in

SDL_image equivalent of https://github.com/libsdl-org/SDL/pull/5955, https://github.com/libsdl-org/SDL_ttf/pull/238 and https://github.com/libsdl-org/SDL_image/pull/295
This allows absolute paths for e.g. `--libdir` when using autotools' `configure` script.

autoconf: use ax_compute_relative_paths

---

cmake/Findlibxmp-lite.cmake
cmake/Findlibxmp.cmake

I was trying to compile `SDL_mixer` for `PS2` using the `cmake` functionality and it was always failing to try to find `libxmp`, however, it was properly installed.
After the change is done in this PR the library is properly detected.
Cheers

Fix issue finding libxmp dependency

---

CMakeLists.txt

Initialize `SDL2MIXER_(OPUS|VORBIS|VORBIS_VORBISFILE)_SHARED` with `${SDL2MIXER_DEPS_SHARED}`.
Fixes #443

cmake: initialize all *_SHARED variables with ${SDL2MIXER_DEPS_SHARED}

---

CMakeLists.txt

Fixes #458 
`BUILD_TESTING` does not need to be set, as the option is not used in there and no [`enable_testing`](https://cmake.org/cmake/help/latest/command/enable_testing.html) is called.

cmake: disable OP_DISABLE_EXAMPLES for vendored opusfile

---

include/SDL_mixer.h
src/mixer.c
src/music.c
src/music.h

This call allows cheaper pausing/resuming of the whole audio processing without pausing every playing channel or music stream.
For example, this call can be used to pause the entire audio playback when the game is not focused.
Note: the "pause_async_music" call is required for music which is playing asynchronously from the main audio output processor, for example, OS Native MIDI. ~~However, the stuff doesn't affect CMD Music which will still play (however, never tested this as I never used CMD music for my needs)~~ Tested this, and it works, because it uses SIGSTOP and SIGCONT signals were literally suspended/resumes the running process.

Added Mix_PauseAudio() call to suspend/resume entire audio output

---

src/mixer.c

At the moment SDL’s sample rate conversion requests a really big buffer which is 4x the necessary size when the target format is 16 bit integer. In some cases we even saw buffers 6x the necessary size. This change ensures that after format conversion only the necessary buffer size is kept.

Fix huge memory waste with resampled sound samples

---

src/mixer.c

Sorry, I previously forgot to error check the return value of SDL_realloc.
This is a minimal way of error handling, since I am not sure how realloc errors are appropriately handled in the code base.
So, feel free to edit the PR branch or let me know how I should change it.

Add missing error handling to SDL_realloc call

---

configure.ac
include/SDL_mixer.h
src/codecs/music_cmd.c
src/codecs/music_drflac.c
src/codecs/music_drmp3.c
src/codecs/music_flac.c
src/codecs/music_fluidsynth.c
src/codecs/music_gme.c
src/codecs/music_gme.h
src/codecs/music_modplug.c
src/codecs/music_mpg123.c
src/codecs/music_nativemidi.c
src/codecs/music_ogg.c
src/codecs/music_ogg_stb.c
src/codecs/music_opus.c
src/codecs/music_timidity.c
src/codecs/music_wav.c
src/codecs/music_wavpack.c
src/codecs/music_xmp.c
src/music.c
src/music.h

This is a partial merge of the work by @Wohlstand referenced in #233.
- ~Grabs the latest GME from https://bitbucket.org/mpyne/game-music-emu/src/master/ (commit `b3d158`)~
- Grabs music_gme.c and edits to music.c from https://github.com/WohlSoft/SDL-Mixer-X (commit `bed335`)
- Modifies `music_gme.c` to use a new `GME_StartTrack`, which is simpler to work with than the "process string args" approach that exists in the fork. With this, a single `Mix_Music` handle can be used and its track changed at any time
- Modifies `music_gme.c` to better match the code style in other files (probably could use more work here)
This is working for me when compiling with Emscripten and running in the browser. I verified these formats work:
- gbs
- nsf
- spc
- vgm
I don't have an `m3u`. There are probably …

Add GME for video game music support

---

src/codecs/music_wavpack.c

There is a crash that will happen when attempting to open an invalid or non-WavPack file by WAVPACK_CreateFromFile() call. There is an attempt to close the RW context with a NULL value.

Fixed crash at WavPack module

---

CMakeLists.txt
cmake/PrivateSdlFunctions.cmake

Check existence of `signal.h` and `setbuf` for samples.
Fixes #489

cmake: check existence of signal.h and setbuf for samples (SDL2)

---

CMakeLists.txt

cmake: check existence of signal.h and setbuf for samples (SDL3)

---

cmake/Findlibxmp-lite.cmake

Fixes #497
The `find_path` might pick up the include path of libxmp (instead of libxmp-lite) when both are installed.
But is this an issue? It looks like these are the same for both libraries.
This is only an issue when the installed libxmp and libxmp-lite come from a different version.

cmake: fix Findlibxmp-lite.cmake

---

CMakeLists.txt
cmake/FindSndFile.cmake
cmake/SDL3_mixerConfig.cmake.in
src/codecs/load_sndfile.c
src/codecs/load_sndfile.h
src/mixer.c

This PR adds support for loading sounds via libsndfile in `Mix_LoadWAV_RW()` to make use of its extended format support, which by far exceeds the ability to load merely WAV/RIFF format files.
Pendant to https://github.com/libsdl-org/SDL/pull/7334

load sounds via libsndfile

---

playwave.c
src/effect_position.c
src/music.c

No volatile keyword need right ? 
if there is an issue, it should be done with mutex / atomic

Remove unneed 'volatile' keyword

---

src/mixer.c

Just fixes a build error introduced by the use of `SDL_atomic_t` in mixer.c instead of `SDL_AtomicInt`

Update mixer.c to use SDL3 Atomic type

---

src/mixer.c

In a recent update to my app's dependencies, I noticed that my channel finished callback, which simply frees the current chunk with `Mix_FreeChunk`, was causing a stack overflow through infinite recursion. This appears to stem from a change in SDL2_mixer 2.6.0 that moved some logic for halting channels around - the channel finished callback is now called *before* setting the channel as not playing, which means that calling any functions that may attempt to halt the channel, including `Mix_FreeChunk`, inside the callback will result in an infinite loop.
This PR adjusts `Mix_HaltChannel_locked` to call `_Mix_channel_done_playing` *after* setting the channel to not playing, which will prevent these sorts of loops. Note that I have yet to test this change, but it shouldn't result in anything …

Fix potential infinite loop in `Mix_FreeChunk` when called in a channel finish callback

---

src/codecs/music_fluidsynth.c

Ensure that when playing a track it starts from the beginning.
Fixes #519

Add seek, tell, and duration to fluidsynth

---

CMakeLists.txt
cmake/FindFLAC.cmake
cmake/FindFluidSynth.cmake
cmake/FindOpusFile.cmake
cmake/FindSndFile.cmake
cmake/FindVorbis.cmake
cmake/Findgme.cmake
cmake/Findlibxmp-lite.cmake
cmake/Findlibxmp.cmake
cmake/Findmodplug.cmake
cmake/Findmpg123.cmake
cmake/Findtremor.cmake
cmake/Findwavpack.cmake
cmake/PkgConfigHelper.cmake
cmake/SDL3_mixerConfig.cmake.in

This PR brings a set of changes that should help searching for dependencies. Feedback is greatly appreciated!
Here is a summary of the changes.
FluidSynth exports the target `FluidSynth::libfluidsynth`.
In the exported config, the casing of `find_dependency(MPG123)` should be `mpg123`, and `opusfile::opusfile` should be `OpusFile::opusfile`.
While the config file was already configured using the `configure_package_config_file` helper, it did not have a `@PACKAGE_INIT@`.
When expanded, it provides the `set_and_check` and `check_required_components` macros, as well as setting `PACKAGE_PREFIX_DIR` to the correct directory.
This property [does not seem to exist](https://cmake.org/cmake/help/latest/search.html?q=INTERFACE_LINK_FLAGS). The `INTERFACE_LINK_OPTIONS` property seems to be what was …

CMake: Improve dependency searching

---

src/music.c

Without this condition, RIFF MIDI (.rmi) files will be misdetected.

music.c: Added proper detection of RIFF MIDI files

---

src/mixer.c

Currently, in the `main` branch, in a situation when `Mix_FadeOutChannel()` is called before the end of the playback, but when there is less than `ms` milliseconds left before the end of the track, there will be two calls of `Mix_ChannelFinished()` callback instead of one - the first is when playback is finished, and the second is when the fade timer expires. This may lead to various issues (e.g. to the double-free issue when `Mix_ChannelFinished()` callback is used to release the `Mix_Chunk`).

Prevent a double call of the Mix_ChannelFinished() callback when using Mix_FadeOutChannel()

---

examples/playmus.c
examples/playwave.c
include/SDL3/SDL_mixer.h
src/codecs/load_aiff.c
src/codecs/load_voc.c
src/codecs/music_drflac.c
src/codecs/music_drmp3.c
src/codecs/music_flac.c
src/codecs/music_fluidsynth.c
src/codecs/music_gme.c
src/codecs/music_modplug.c
src/codecs/music_mpg123.c
src/codecs/music_ogg.c
src/codecs/music_ogg_stb.c
src/codecs/music_opus.c
src/codecs/music_timidity.c
src/codecs/music_wav.c
src/codecs/music_wavpack.c
src/codecs/music_xmp.c
src/codecs/timidity/timidity.c
src/mixer.c
src/music.c

This is a draft PR until the new audio API is merged into SDL3, but once that is, this will update SDL_mixer to work with it.
This makes two API changes to SDL mixer.
First, Mix_OpenAudio is simplified, and can even be called as `Mix_OpenAudio(0, NULL);` and probably get the exact desired result in most use cases.
Second, Mix_OpenAudioDevice is gone, as redundant.
Internally, this is the most minimal patch that gets SDL_mixer working again, which is to say it cleans up a few things that expected SDL_AudioSpec to have more fields, and it changes the library to use a single SDL_AudioStream with a callback instead of the SDL2 audio device callback.
One could certainly get more creative, turning each SDL_mixer channel into an audio stream bound to the device, each of them firing a callback …

Updated for new SDL3 audio API.

---

src/codecs/mp3utils.c

Via CLang, I accidentally found that `.pos` field of the `mp3file_t` structure was not being initialized at the read_id3v2_from_mem() call. So, I added that missing initialisation and fixed that problem.

[SDL3] mp3util.c: Fixed the unitialised "pos" at read_id3v2_from_mem()

---

src/codecs/mp3utils.c

Via CLang, I accidentally found that `.pos` field of the `mp3file_t` structure was not being initialized at the read_id3v2_from_mem() call. So, I added that missing initialisation and fixed that problem.

[SDL2] mp3util.c: Fixed unitialized "pos" at read_id3v2_from_mem()

---

.wikiheaders-options

https://github.com/libsdl-org/SDL_mixer/issues/542
`wikiheaders.pl` has [`--warn-about-missing`](https://github.com/libsdl-org/SDL_mixer/blob/489716b38b7293f2539f37714dc0890cbace37c5/build-scripts/wikiheaders.pl#L36) to force the value to 0.
@icculus Is this ok? Or is a `--no-warn-about-missing` option preferred?

wikiheaders: don't warn about missing files by default

---

src/SDL_mixer.sym

Adds a function to SDL_mixer.sym that was previously missed and was causing me some linker errors.

Add Mix_ChannelFinished to SDL_mixer.sym

---

include/SDL3_mixer/SDL_mixer.h
src/SDL_mixer.sym
src/mixer.c

Adds a couple helper functions similar to `Mix_HaltGroup` that make it easy to pause and resume groups of channels together. In my game I group in-game sounds so I can easily pause and resume them when the game pauses.

Add Mix_PauseGroup and Mix_ResumeGroup functions

---

src/codecs/music_flac.c
src/music.c

The first commit of this PR is for fixing the detection of FLAC files when it is encapsulated in an OGG transport later (currenty these kind of files go down the Ogg-Vorbis path, which cannot handle it).
The second commit fixes the handling of such files in the libflac backend (the drflac backend seems to already take care of this).
I wrote and tested these commits against the SDL2 branch. With few small porting changes I'm making this PR against `main`. If the maintainers wish I'd be happy to also open the SDL2 branch backport PR for this.

Fix flac-in-ogg handling

---

src/codecs/music_ogg_stb.c
src/codecs/stb_vorbis/stb_vorbis.h

The following 4 patches are based on PR submissions at mainstream.
I modified most of the patches and notified the patch author about
them.
(1) Fix CVE-2023-45676 and CVE-2023-45677 (integer overflow in setup_malloc()):
Based on the patches by Jaroslav Lobačevski (@JarLob) submitted
to mainstream at: https://github.com/nothings/stb/pull/1554 and https://github.com/nothings/stb/pull/1555
GHSL-2023-166/CVE-2023-45676: Multi-byte write heap buffer overflow in start_decoder()
GHSL-2023-167/CVE-2023-45677: Heap buffer out of bounds write in start_decoder()
Test files (for convenience): [1554.ogg.zip](https://github.com/libsdl-org/SDL_mixer/files/13630602/1554.ogg.zip), [1555.ogg.zip](https://github.com/libsdl-org/SDL_mixer/files/13630603/1555.ogg.zip)
(2) Fix CVE-2023-45679 and CVE-2023-45680: …

stb_vorbis CVE fixes

---

src/codecs/minimp3/minimp3_ex.h

It's a still-born extension that no one uses, no player supports, and no tag library parses.
And it's not impossible to hit it as a false positive..
(The removal has already been suggested to mainstream at https://github.com/lieff/minimp3/issues/66)
---
If https://github.com/mackron/dr_libs/issues/263 doesn't get  resolved and we won't go back to dr_mp3, please merge this and also cherry-pick to SDL3 branch as well.

minimp3: remove TAG+ support

---

src/codecs/music_wavpack.c

`ftruncate` is used through`WavpackOpenFileInput`.
Since SDL_mixer uses `WavpackOpenFileInputEx` instead of `WavpackOpenFileInput`, don't look for `WavpackOpenFileInput`.
Depends on https://github.com/libsdl-org/WavPack/pull/2
Fixes #585

wavpack: WavpackOpenFileInput is not used, so don't load it

---

examples/playmus.c

In addition, fflush(stdin) is undefined behaviour, so remove it.

examples/playmus: Prevent stack smashing on long input strings

---

src/codecs/music_fluidsynth.c

The fluidsynth player would resume from the point when the track was stopped instead of the beginning when Play was called. This was the desired behaviour for the unsupported Pause/Resume functions, so I moved the definitions to those functions and added new Start/Stop functions that seek to the beginning of the track before playing.
I previously submitted a larger version of this patch that included seek/tell but the ticks in fluidsynth turned out to be problematic so this version only covers stop/play, which fixes the jukebox functionality in CorsixTH.

Stop/Start/Pause/Resume for Fluidsynth

---

src/codecs/native_midi/native_midi_common.c

if allocation of mididata->track ever fails we'd still be dereferencing it under 'bail'
Unless I'm missing something...

native_midi_common.c (ReadMIDIFile): fix possible NULL ptr dereference.

---

src/mixer.c

changed SDL_AUDIO_DEVICE_DEFAULT_OUTPUT to SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK
https://github.com/libsdl-org/SDL/commit/38f0214e8a579664d19c3eb95ff1df660e519420

update after SDL_AUDIO_DEVICE_DEFAULT_OUTPUT rename

---

src/mixer.c

Hi! I recently noticed that Mix_AllocateChannels didn't have a useful return value, it just returned the same number of channels that I passed in as parameter. Therefore I found out that there is not a single error checking on the success of the allocation, and in the case of an unsuccessful allocation an invalid address would have been used.
Solution: I added the missing error checking, the reallocation now uses a temporary pointer to check the success of the allocation, if the allocation was successful it will use the new pointer otherwise it sets an error, and the original pointer remains intact. Also now you can check the return value for useful information on the success of the allocation.

Mix_AllocateChannels realloc fix

---

examples/playwave.c
include/SDL3_mixer/SDL_mixer.h
src/effect_position.c
src/effect_stereoreverse.c
src/mixer.c

Update to newest SDL

---

src/codecs/music_opus.c
src/codecs/music_wavpack.c
src/codecs/music_xmp.c

The existing placement of `__attribute__ ((optnone))` does not spit an error with Clang, because Clang is indifferent to the sequence here, but it breaks build with GCC.
Fix this finally.

Unbreak build with gcc on macOS

---

src/codecs/music_flac.c
src/codecs/music_gme.c
src/codecs/music_modplug.c
src/codecs/music_mpg123.c
src/codecs/music_ogg.c

@slouken Please review.
These were missed, because I did not need them for building 2.8.0 release in a config which MacPorts uses. I do not have SDL3 so cannot test the master, but the changes are identical, so should work the same way.
Credits to @sezero for pointing this out.
See: https://github.com/libsdl-org/SDL_mixer/pull/627#issuecomment-2287161791

music_*: fix remaining cases of incorrect attribute placement

---

CMakeLists.txt
examples/playwave.c

I think there's something wrong when running playwave with `-F` (reverse sound):
when playing `sample.wav` from SDL, it finished in half the expected time.

playwave: use SDL_test to parse arguments + don't use compiler conditionals

---

include/SDL3_mixer/SDL_mixer.h

Mix_LockAudio is mentioned several times in the method documentation, but the method itself is nowhere to be found. I suspect that it used to be there, but then it was removed.

Removed Mix_LockAudio and made some minor edits

---

Makefile.in
configure
configure.ac
sdl2_mixer-config.cmake.in

Build CMake list containing CMake targets in configure.ac
I tested this with:
```cmd
mkdir build
cd build
../configure --prefix=$PWD/prefix --enable-music-mod-modplug-shared=no --enable-music-mod-xmp-shared=no --enable-music-midi-fluidsynth-shared=no --enable-music-gme-shared=no --enable-music-ogg-vorbis-shared=no --enable-music-ogg-tremor-shared=no --enable-music-flac-libflac-shared=no --enable-music-mp3-mpg123-shared=no --enable-music-opus-shared=no --enable-music-wavpack-shared=no
make
make install
cmake -S ../cmake/test -B /tmp/sdl2-mixer-autotools-cmake-test-build --fresh -DCMAKE_PREFIX_PATH=$PWD/prefix
cmake --build /tmp/sdl2-mixer-autotools-cmake-test-build
```
Fixes #655

autotools: set CMake libraries directly in configure.ac

---

Makefile.in

Cherry-picked from SDL2 commit d55b3da936d24af2f44526807f9481b8e8205e86.

Fixed linker order so -lmingw32 comes before -lSDLmain (SDL 1.2)

---

src/codecs/stb_vorbis/stb_vorbis.h

Requesting the data one byte at a time can be prohibitively expensive, especially when the SDL_RWops isn't backed by constant memory but routed through PhysicsFS for example.
This change introduces a 2kb buffer, which feels small enough to not add too much overhead and is the same size as used by libvorbisfile. In my measurements, using a larger buffer no longer made a significant difference when starting to play an OGG file.
Testing with an uncompressed OGG file read from zip file, timing the call to `Mix_LoadMUS_RW`:
* No buffer: ~ 47 ms
* 10 bytes: ~ 5.2 ms
* 100 bytes: ~ 1.1 ms
* 1 kb: ~ 0.62 ms
* 2 kb: ~ 0.6 ms
* 8 kb: ~ 0.58 ms
When using the libvorbisfile backend it takes about 0.2 ms.
See #670.

stb_vorbis: Use a buffer to cache SDL_RWops reads

---

src/codecs/native_midi/native_midi_linux_alsa.c

This PR implements support for sending SysEx messages to MIDI devices using the native MIDI ALSA implementation.
Tested by playing back various SMF files containing SysEx messages and comparing them to aplaymidi using aseqdump.
```
$ ALSA_OUTPUT_PORTS=aseqdump ./playmus file.mid
$ ALSA_OUTPUT_PORTS=aseqdump aplaymidi file.mid
```

native_midi_linux_alsa: Add support for System Exclusive messages

---

src/codecs/native_midi/native_midi_linux_alsa.c

```c
In file included from /path/to/SDL_mixer-git/src/codecs/native_midi/native_midi_linux_alsa.c:39:
/usr/include/alsa/asoundef.h:30:2: warning: #warning "use #include <alsa/asoundlib.h>, <alsa/asoundef.h> should not be used directly" [-Wcpp]
30 | #warning "use #include <alsa/asoundlib.h>, <alsa/asoundef.h> should not be used directly"
|  ^~~~~~~
```
alsa 1.2.14
gcc 14.2.1
clang 19.1.7

Don't include alsa/asoundef.h directly

---

src/decoder_wav.c

```c
[ 61%] Building C object CMakeFiles/SDL3_mixer-shared.dir/src/decoder_wav.c.o
/path/to/SDL_mixer/src/decoder_wav.c: In function ‘WAV_init_track’:
/path/to/SDL_mixer/src/decoder_wav.c:1384:58: warning: ‘SDL_calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
1384 |         state->output.data = (Sint16 *)SDL_calloc(sizeof(Sint16), state->output.size);
|                                                          ^~~~~~
/path/to/SDL_mixer/src/decoder_wav.c:1384:58: note: earlier argument should specify number of elements, later size of each element
```
Swapping the arguments gets rid of the warning.

Fixed warning: calloc-transposed-args

---

src/SDL_mixer_metadata_tags.c

The comparison `i >= 0` is always true because `i` is an unsigned type.
```c
[  6%] Building C object CMakeFiles/SDL3_mixer-shared.dir/src/SDL_mixer_metadata_tags.c.o
/path/to/SDL_mixer/src/SDL_mixer_metadata_tags.c: In function ‘parse_id3v1_ansi_string’:
/path/to/SDL_mixer/src/SDL_mixer_metadata_tags.c:99:37: warning: comparison of unsigned expression in ‘>= 0’ is always true [-Wtype-limits]
99 |     for (size_t i = src_len - 1; (i >= 0) && (src_buffer[i] == ' '); i--) {
|                                     ^~
```
This commit uses a do-while loop instead.
_Might be a bit more "chatty". :)_
_4 lines vs 12 lines_

SDL_mixer_metadata_tags.c:parse_id3v1_ansi_string(): Fixed "always true" expression

---

src/decoder_opus.c
src/decoder_stb_vorbis.c
src/decoder_vorbis.c

On error, some locally allocated memory isn't freed before returning from a function.
This commit adds those `SDL_free()` calls.
<details><summary>Warnings</summary>
<p>
```c
[ 38%] Building C object CMakeFiles/SDL3_mixer-shared.dir/src/decoder_opus.c.o
/path/to/SDL_mixer/src/decoder_opus.c:154:16: warning: Potential leak of memory pointed to by 'adata' [clang-analyzer-unix.Malloc]
154 |         return set_op_error("ov_open_callbacks", rc);
|                ^
/path/to/SDL_mixer/src/decoder_opus.c:136:9: note: Assuming 'of' is non-null
136 |     if (!of) {
|         ^~~
/path/to/SDL_mixer/src/decoder_opus.c:136:5: note: Taking false branch
136 |     if (!of) {
|     ^
/path/to/SDL_mixer/src/decoder_opus.c:142:9: note: Assuming the condition is false
142 |     if (SDL_SeekIO(io, 0, …
```

Freeing memory on error

---

src/SDL_mixer.c

Fixes #720, basically the same problem fixed in predecoding in cf4befdf42de2ffacd50ead3c4195d96a0d93123

Fix double clamping of precached data

---

src/SDL_mixer_metadata_tags.c
src/decoder_opus.c
src/decoder_voc.c
src/decoder_wav.c
src/decoder_wavpack.c

```c
[  6%] Building C object CMakeFiles/SDL3_mixer-shared.dir/src/SDL_mixer_metadata_tags.c.o
/path/to/SDL_mixer/src/SDL_mixer_metadata_tags.c:1039:17: warning: redundant explicit casting to the same type 'char *' as the sub-expression, remove this casting [readability-redundant-casting]
1039 |     char *ptr = (char *) SDL_strchr(str, '/');  // see if it has both track _and_ total tracks.
|                 ^~~~~~~~
/usr/include/string.h:246:14: note: source type originates from the invocation of this function
246 | extern char *strchr (const char *__s, int __c)
|        ~~~~~~^
[ 38%] Building C object CMakeFiles/SDL3_mixer-shared.dir/src/decoder_opus.c.o
/path/to/SDL_mixer/src/decoder_opus.c:230:18: warning: redundant explicit casting to the same type 'int' as the sub-expression, remove …
```

Removed redundant casts

---

src/SDL_mixer.c

`SDL_mixer_internal.h` defines `SDL_MIXER_NEED_SCALAR_FALLBACK`, but `NEED_SCALAR_FALLBACK` was checked.

Fix scalar fallback

---

src/SDL_mixer_spatialization.c

Neon intrinsics "vcopyq_laneq_f32" is undeclared.
It is defined in <arm_neon.h>, but not activated because of __ARM_FP value.
So, unactivate NEON intrinsics for spatialization on Android.

Fixed bug #733: build error on android with NEON intrinsics

---

src/decoder_voc.c

If any of these switch cases are trigger in between `VOC_LOOP` and `VOC_LOOPEND` the `adata->blocks` gets reallocated and `loop_start` is invalidated:
```c
VOC_DATA
VOC_DATA_16
VOC_CONT
VOC_SILENCE
```
The initial issue was https://github.com/libsdl-org/SDL_mixer/issues/726 and fixed the reallocation issue at the end of the loop in `VOC_LOOPEND`, but then others appeared.
This commit declares a variable outside the while loop and switch statement to preserve the variable `loop_start->loop_count` when it is first allocated. This variable is not affected when reallocations happen.
<details><summary>Warning</summary>
<p>
```c
[ 45%] Building C object CMakeFiles/SDL3_mixer-shared.dir/src/decoder_voc.c.o
/path/to/SDL_mixer/src/decoder_voc.c:291:37: warning: Use of memory after it is freed …
```

decoder_voc: fix possible use-after-free again

---

include/SDL3_mixer/SDL_mixer.h

Detected by Debian's Lintian tool, via spellchecking the installed man pages.

doc: Fix spelling of "arbitrarily"

---

cmake/FindFluidSynth.cmake

This was changed in https://github.com/FluidSynth/fluidsynth/pull/1546
Closes #755

cmake: fluidsynth package can contain versioned fluidsynth libraries

---

VisualC/SDL_mixer.sln
VisualC/SDL_mixer.vcxproj

Currently, the Visual Studio project here only builds the SINEWAVE and RAW decoders. This adjusts the settings to build all the normal decoders by adjusting the names and includes that haven't been updated since the big rewrite.
It also removes the SDL3 subproject, which was removed from the repo in January. https://github.com/libsdl-org/SDL_mixer/commit/4d068edb9dcfd8e7e9f18ebf6214f49fe995ff6e
- I was trying to use only includes from the external/ directory to avoid the need for includes inside the Visual Studio project folder, but I couldn't get that to work for opusfile and wavpack. I tried using the xyz_HEADER defines to redefine the headers to "<wavpack.h> instead of <wavpack/wavpack.h>", for example, and then added external/wavpack/include as an additional directory, but this didn't …

Update Visual Studio settings from SDL2-times
