libsdl-org/SDL_mixer

- src/codecs/music_mad.c
This update I developed a while ago for the MixerX fork. It allows reporting the song duration and the current time position while playing the song.
#233
> music_mad.c: Added the support for the Tell and Duration

- .gitignore
- fluidsynth.c
- fluidsynth.h
It's the similar refactoring I made at the mainstream branch with the SDL2.
> SDL 1.2 fluidsynth refactor

- src/mixer.h
- src/music.h
- add include guards to mixer.h
- move #include "SDL_mixer.h" under the guard of music.h
> fix include guards

- src/effect_position.c
> do not use volatiles in (possible) long loops of _Eff_position_*

- src/mixer.c
- fix memory leak in case a chunk with effect(s) is freed while it is playing
- fix race condition in Mix_HaltChannel due to non-locked audio
> fix memory leak in Mix_FreeChunk + race condition in Mix_HaltChannel

- SDL2_mixer.pc.in
- configure.ac
> Add the required libraries to SDL2_mixer.pc

- src/mixer.c
> mixer.c: Clean-up white-spaces

- src/codecs/music_drflac.c
Fixed the crash because of a null-pointer access attempt, and make the proper loading of meta-data (sample-rate can't be accessed if not handled via `DRFLAC_METADATA_BLOCK_TYPE_STREAMINFO` block separately).
> music_drflac.c: Fixed the crash on looped file loading

- VisualC/pkg-support/cmake/sdl2_mixer-config-version.cmake
- VisualC/pkg-support/cmake/sdl2_mixer-config.cmake
> cmake: fix location of include dir for VC sdk

- src/effect_position.c
- src/effect_stereoreverse.c
> effect_position.c, effect_stereoreverse.c: small whitespace fix

- README.txt
Fixes #430
@ricardobusta
Does this clear things up a bit?
> Expand CMake line a bit in README.txt

- CMakeLists.txt
Follow-up of https://github.com/libsdl-org/SDL_net/pull/61
> cmake: always install SDL2_mixer.pc

- src/codecs/native_midi/native_midi_common.c
Free mididata->track in error path
> Fix memory leak in ReadMIDIFile

- .gitmodules
- Xcode/xmp-lite/xmp-lite.xcodeproj/project.pbxproj
@slouken: make sure that this is OK for android, xcode and msvc builds.
> switch libxmp to latest revision

- src/codecs/music_wavpack.c
Avoids SDL's resampler e.g. for 16 bit files with 16 bit output setup,
which probably would be the most common case.  Wavpack library returns
the samples in 8, 16, 24, or 32 bit depths, but always in an int32_t[]
buffer in host-endian format; we now move the 8 bit and 16 bit samples
properly before feeding to SDL_AudioStream.
@icculus, @slouken: Please review for whether this would be beneficial
and if not, I will discard this.
P.S.: In case this accepted: Does it make any sense to further convert
8 bit samples from S8 to U8 format?
> music_wavpack: do not setup buffer in S32 format for 8/16 bit sources.

- src/mixer.c
Use SDL_AudioStream instead of AudioCVT for Mix_LoadWAV_RW()
(if we plan to remove AudioCVT in https://github.com/libsdl-org/SDL/issues/6632 )
> Use SDL_AudioStream instead of AudioCVT for Mix_LoadWAV_RW()

- src/mixer.c
Simplify code using SDL_ConvertAudioSamples
after the function gets merged in SDL3
> Simplify code using SDL_ConvertAudioSamples

- include/SDL3/SDL_mixer.h
- playmus.c
- playwave.c
- src/codecs/load_aiff.c
- src/codecs/load_sndfile.c
- src/codecs/load_voc.c
- src/codecs/music_drflac.c
- src/codecs/music_drmp3.c
- src/codecs/music_flac.c
- src/codecs/music_fluidsynth.c
- src/codecs/music_gme.c
- src/codecs/music_modplug.c
- src/codecs/music_mpg123.c
- src/codecs/music_ogg.c
- src/codecs/music_ogg_stb.c
- src/codecs/music_opus.c
- src/codecs/music_wav.c
- src/codecs/music_wavpack.c
- src/codecs/music_xmp.c
- src/codecs/native_midi/native_midi_win32.c
- src/codecs/timidity/timidity.c
- src/effect_position.c
In response to [this changes](https://github.com/libsdl-org/SDL/pull/7671) from SDL.
> add SDL_ prefix to AUDIO_* constants

- music_flac.c
Previously when trying to play a 24bit flac in a loop (eg. with playmus -l) the application hung on exit because FLAC_getsome kept trying to decode data while holding the audio lock.
Add earlier 16bit check to prevent starting to play the file at all. And stop on error status codes from FLAC__stream_decoder_get_state to prevent a hang when flac decode fails.
> flac: earlier 16bit check and prevent error hang

- CMakeLists.txt
- SDL2_mixerConfig.cmake.in
- cmake/FindFLAC.cmake
- cmake/FindFluidSynth.cmake
- cmake/FindOpusFile.cmake
- cmake/FindVorbis.cmake
- cmake/Findgme.cmake
- cmake/Findlibxmp-lite.cmake
- cmake/Findlibxmp.cmake
- cmake/Findmodplug.cmake
- cmake/Findmpg123.cmake
- cmake/Findtremor.cmake
- cmake/Findwavpack.cmake
- cmake/PkgConfigHelper.cmake
This PR is a backport of #504 for the SDL2 branch.
> [SDL2] CMake: Improve dependency searching

- include/SDL3/SDL_mixer.h
Detected by Debian's Lintian tool.
> doc: Fix some typos

- .github/workflows/main.yml
- CMakeLists.txt
See https://github.com/libsdl-org/SDL_ttf/pull/349
> cmake: use MACHO* properties to set macho version

- include/SDL3_mixer/SDL_mixer.h
- src/mixer.c
- src/music.c
This is after https://github.com/libsdl-org/SDL/pull/9718. Reviews / improvements are welcome. (CC: @0x1F9F1 )
> update after SDL3 SDL_MIX_MAXVOLUME removal and SDL_MixAudio api change

- src/codecs/load_voc.c
- src/codecs/music_wav.c
- src/codecs/timidity/instrum.c
- src/codecs/timidity/readmidi.c
- src/effect_position.c
https://github.com/libsdl-org/SDL/pull/10010
> update after SDL_Swap rename in SDL3

- src/SDL_mixer_internal.h
After spending much time in the debugger, I finally found out why sfx weren't working for me.
> fix MIX_PROP_DECODER_FREQ_NUMBER

- include/SDL3_mixer/SDL_mixer.h
> Fix docs typo

- src/decoder_wav.c
Resolves https://github.com/libsdl-org/SDL_mixer/issues/727
> decoder_wav.c:AddLoopPoint(): Move start/stop check to top
